import { createHash } from 'crypto';
import { nanoid } from 'nanoid';
import { generateTTS } from '@/lib/audio/tts-providers';
import type { TTSProviderId } from '@/lib/audio/types';
import { fingerprintSpeechVoice, speechVoiceMatches } from '@/lib/audio/voice-fingerprint';
import { CosStorage } from '@/lib/server/cos-storage';
import { CourseRepository } from '@/lib/server/db/course-repository';
import { CourseRevoiceRepository } from '@/lib/server/db/course-revoice-repository';
import { getDatabasePool } from '@/lib/server/db/pool';
import { isServerConfiguredProvider, isServerTTSProviderDisabled, resolveTTSApiKey, resolveTTSBaseUrl, resolveTTSModel } from '@/lib/server/provider-config';
import type { StageTeacherVoiceConfig } from '@/lib/teacher/apply-teacher-voice';
export type CourseRevoiceStatus = 'queued'|'running'|'succeeded'|'failed'|'cancelled'|'conflict';
type Json=Record<string,unknown>; type RevoiceItem={sceneId:string;actionId:string;text:string;status:'queued'|'done'|'failed';audioId?:string;audioUrl?:string;error?:string;attempts?:number};
export type CourseRevoiceJob={id:string;course_id:string;requested_by:string;status:CourseRevoiceStatus;voice:StageTeacherVoiceConfig;snapshot:{stage:Json;scenes:Json[];outlines:unknown[]};source_updated_at:string;items:RevoiceItem[];total_items:number;completed_items:number;failed_items:number;message:string;error?:string|null;created_at:string;updated_at:string};
export type CourseRevoiceErrorCode='VOICE_NOT_SERVER_CONFIGURED'|'VOICE_PROVIDER_DISABLED'|'VOICE_BROWSER_ONLY'|'NO_REVOICE_ITEMS'|'REVOICE_DATABASE_MIGRATION_REQUIRED'|'REVOICE_DATABASE_UNAVAILABLE'|'REVOICE_AUTH_SYNC_REQUIRED'|'REVOICE_CREATE_FAILED';
export class CourseRevoiceError extends Error { constructor(public readonly code:CourseRevoiceErrorCode,message:string,public readonly status:number){super(message);this.name='CourseRevoiceError'} }
const BATCH=12, CONCURRENCY=3, MAX_ATTEMPTS=3;
export function isRevoiceNoopError(error:unknown){return error instanceof Error&&error.message==='所有语音片段已使用选定音色，无需重新配音。'}
export function describeCourseRevoiceError(error:unknown):CourseRevoiceError {if(error instanceof CourseRevoiceError)return error;const databaseError=error as {code?:string}|null;if(databaseError?.code==='42P01')return new CourseRevoiceError('REVOICE_DATABASE_MIGRATION_REQUIRED','服务器尚未完成配音任务数据库迁移，请执行 0008_learning_analytics_and_revoice.sql 后重试。',503);if(databaseError?.code==='23503')return new CourseRevoiceError('REVOICE_AUTH_SYNC_REQUIRED','当前登录用户尚未同步到课程数据库，请重新登录后重试。',409);if(databaseError?.code?.startsWith('08'))return new CourseRevoiceError('REVOICE_DATABASE_UNAVAILABLE','配音任务数据库暂时不可用，请稍后重试。',503);return new CourseRevoiceError('REVOICE_CREATE_FAILED','无法创建重新配音任务，请稍后重试。',500)}
function provider(id:string){return id.endsWith('-tts')?id:`${id}-tts`}
export function assertServerRevoiceVoice(voice:StageTeacherVoiceConfig){const providerId=provider(voice.providerId);if(providerId==='browser-native-tts')throw new CourseRevoiceError('VOICE_BROWSER_ONLY','浏览器本地音色不能用于整课重新配音，请选择已在服务器配置的 AI 音色。',422);if(isServerTTSProviderDisabled(providerId))throw new CourseRevoiceError('VOICE_PROVIDER_DISABLED','所选 AI 音色服务已被管理员禁用。',422);if(!isServerConfiguredProvider('tts',providerId))throw new CourseRevoiceError('VOICE_NOT_SERVER_CONFIGURED','所选 AI 音色尚未在服务器配置，无法执行整课重新配音。',422);return {...voice,providerId}}
function narrationItems(scenes:Json[]){return scenes.flatMap(scene=>{const sceneId=typeof scene.id==='string'?scene.id:'';const actions=Array.isArray(scene.actions)?scene.actions as Json[]:[];return actions.flatMap((action,index)=>action.type==='speech'&&typeof action.text==='string'&&action.text.trim()&&sceneId?[{sceneId,actionId:typeof action.id==='string'?action.id:`${sceneId}-${index}`,text:action.text.trim(),audioVoiceFingerprint:action.audioVoiceFingerprint}]:[])})}
function speechItems(scenes:Json[],voice:StageTeacherVoiceConfig):RevoiceItem[]{return narrationItems(scenes).filter(item=>!speechVoiceMatches(item.audioVoiceFingerprint,item.text,voice)).map(item=>({sceneId:item.sceneId,actionId:item.actionId,text:item.text,status:'queued' as const}))}
export async function createCourseRevoiceJob(input:{courseId:string;userId:string;voice:StageTeacherVoiceConfig;snapshot:CourseRevoiceJob['snapshot'];sourceUpdatedAt:string}){const voice=assertServerRevoiceVoice(input.voice);if(!narrationItems(input.snapshot.scenes).length)throw new CourseRevoiceError('NO_REVOICE_ITEMS','课程中没有可重新配音的语音片段。',422);const items=speechItems(input.snapshot.scenes,voice);if(!items.length)throw new Error('所有语音片段已使用选定音色，无需重新配音。');return new CourseRevoiceRepository(getDatabasePool()).create({id:nanoid(16),course_id:input.courseId,requested_by:input.userId,status:'queued',voice,snapshot:input.snapshot,source_updated_at:input.sourceUpdatedAt,items,total_items:items.length,completed_items:0,failed_items:0,message:'已加入重新配音队列。',created_at:new Date().toISOString(),updated_at:new Date().toISOString()})}
export async function getCourseRevoiceJob(id:string){return new CourseRevoiceRepository(getDatabasePool()).get(id)}
export async function getLatestCourseRevoiceJob(courseId:string){return new CourseRevoiceRepository(getDatabasePool()).getLatestForCourse(courseId)}
export async function cancelCourseRevoiceJob(id:string,courseId:string){return new CourseRevoiceRepository(getDatabasePool()).cancel(id,courseId)}
async function synthesize(job:CourseRevoiceJob,item:RevoiceItem){const providerId=provider(job.voice.providerId);const result=await generateTTS({providerId:providerId as TTSProviderId,modelId:resolveTTSModel(providerId,job.voice.modelId),voice:job.voice.voiceId,speed:1,apiKey:resolveTTSApiKey(providerId),baseUrl:resolveTTSBaseUrl(providerId)},item.text);const ext=result.format==='mpeg'?'mp3':(result.format||'mp3').replace(/^\./,'');const contentType=ext==='mp3'?'audio/mpeg':`audio/${ext}`;const audio=Buffer.from(result.audio);const hash=createHash('sha256').update(audio).digest('hex');const key=`courses/${job.course_id}/audio/revoice/${job.id}/${hash}.${ext}`;await new CosStorage().putObject(key,audio,contentType);await new CourseRepository(getDatabasePool()).createAsset({ownerUserId:job.requested_by,courseId:job.course_id,kind:'audio',objectKey:key,contentType,sizeBytes:audio.length});return {audioId:`voice_${job.id}_${item.sceneId.slice(0,8)}_${item.actionId.slice(0,8)}`,audioUrl:`/api/course-assets/object?key=${encodeURIComponent(key)}`}}
function describeExecutionFailure(error:unknown){const message=error instanceof Error?error.message:'';if(/Tencent COS|TENCENT_COS|putObject/i.test(message))return '音频上传到课程存储失败，请检查服务器 COS 配置。';if(/api key|credential|unauthori[sz]ed|forbidden/i.test(message))return 'AI 音色服务认证失败，请检查服务器端 TTS 配置。';return '配音任务执行失败，原课程音频未被修改。'}
async function retry(job:CourseRevoiceJob,item:RevoiceItem){let last:unknown;for(let attempt=0;attempt<2;attempt++){try{return await synthesize(job,item)}catch(error){last=error;if(attempt===0)await new Promise(resolve=>setTimeout(resolve,1500))}}throw last}
export function mergeRevoiceResults(snapshot:CourseRevoiceJob['snapshot'],items:RevoiceItem[],voice:StageTeacherVoiceConfig){const done=new Map(items.filter(item=>item.status==='done').map(item=>[`${item.sceneId}:${item.actionId}`,item]));const scenes=snapshot.scenes.map(scene=>({...scene,actions:(Array.isArray(scene.actions)?scene.actions as Json[]:[]).map((action,index)=>{const item=done.get(`${scene.id}:${typeof action.id==='string'?action.id:`${scene.id}-${index}`}`);return item&&action.type==='speech'&&action.text===item.text?{...action,audioId:item.audioId,audioUrl:item.audioUrl,audioVoiceFingerprint:fingerprintSpeechVoice(item.text,voice)}:action})}));return {stage:{...snapshot.stage,teacherVoiceConfig:voice},scenes}}
export async function runCourseRevoiceJob(id:string){const repo=new CourseRevoiceRepository(getDatabasePool()),job=await repo.claim(id);if(!job)return null;try{const items=[...job.items],pending=items.filter(item=>item.status==='queued').slice(0,BATCH);for(let start=0;start<pending.length;start+=CONCURRENCY)await Promise.all(pending.slice(start,start+CONCURRENCY).map(async item=>{const index=items.findIndex(candidate=>candidate.sceneId===item.sceneId&&candidate.actionId===item.actionId);try{items[index]={...item,...await retry(job,item),status:'done'}}catch(error){const attempts=(item.attempts??0)+1;items[index]={...item,status:attempts>=MAX_ATTEMPTS?'failed':'queued',attempts,error:describeExecutionFailure(error)}}}));const completed=items.filter(item=>item.status==='done').length,failed=items.filter(item=>item.status==='failed').length,remaining=items.filter(item=>item.status==='queued').length;if(failed){const error=items.find(item=>item.status==='failed')?.error??'配音任务执行失败，原课程音频未被修改。';return repo.updateRunning(id,{items,completedItems:completed,failedItems:failed,status:'failed',error,message:error,completed:true,lockedUntil:null})}if(remaining)return repo.updateRunning(id,{items,completedItems:completed,message:`正在生成重新配音 ${completed}/${job.total_items}`,lockedUntil:new Date(Date.now()+60000)});const current=await repo.getCourse(job.course_id);if(!current)throw new Error('Course was deleted while revoice was running.');const data=current.content as Partial<CourseRevoiceJob['snapshot']>;if(!data.stage||!Array.isArray(data.scenes))throw new Error('Course content is incomplete.');const final=mergeRevoiceResults({stage:data.stage,scenes:data.scenes,outlines:Array.isArray(data.outlines)?data.outlines:[]},items,job.voice);await repo.updateRunning(id,{items,completedItems:completed});const status=await repo.commit(id,job.course_id,job.source_updated_at,{stage:final.stage,scenes:final.scenes,outlines:Array.isArray(data.outlines)?data.outlines:[],saveState:'ready',audioGeneration:{attempted:true,completedAt:new Date().toISOString(),source:'server-revoice-job'}});return {...job,status:status as CourseRevoiceStatus}}catch(error){const message=describeExecutionFailure(error);console.error('[course-revoice] job execution failed',{jobId:id,message:error instanceof Error?error.message:'Unknown error'});await repo.fail(id,message).catch(()=>undefined);throw error}}
export async function runNextCourseRevoiceJob(){const id=await new CourseRevoiceRepository(getDatabasePool()).nextRunnable();return id?runCourseRevoiceJob(id):null}
